config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :docs
  authenticated :user do 
  	root 'docs#index', as: :authenticated_root 
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :docs       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = current_user.docs
  end

  def show
    # @doc = Doc.find_by(id: params[:id])
  end

  def new
    @doc = current_user.docs.build  
  end
    
  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      # show path
      redirect_to doc_path(@doc)
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @doc.update_attributes(doc_params)
      redirect_to doc_path(@doc)
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find_by(id: params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/docs/edit.html.haml
%h1 Edit doc
= render 'form'

app/views/docs/index.html.haml
%h1 listing docs
- @docs.each do |doc|
	%h2= link_to doc.title, doc_path(doc)
	%p= time_ago_in_words(doc.created_at)
	%p= truncate(doc.content, length:50)

= link_to 'Create Doc', new_doc_path

app/views/docs/new.html.haml
%h1 Create new doc
= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content
= link_to 'Edit', edit_doc_path(@doc)
= link_to 'Destroy', doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"}

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "File cabinet", root_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to "Create Doc", new_doc_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Log in", new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabinet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cabinet
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = render 'layouts/header'
    = yield

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.haml
%h1 This the placeholder!!